name: Checkout Code

on:
  workflow_dispatch: {}
  push:
    branches:
      - daniel

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          repository: shuttler-tw/shuttler-backend
          ref: daniel

      - name: Setup Node Environment
        uses: actions/setup-node@v4
        with:
          node-version: '22.15.0'
      - run: |
          echo "Node version: $(node -v)"
          echo "Installing dependencies..."
          npm install -g pnpm
          pnpm install

      - name: Run ESLint
        id: eslint
        continue-on-error: true
        run: npm run lint

      - name: Run Check Prettier Formatting
        id: prettier
        continue-on-error: true
        run: npm run format:check

      - name: Notify on Discord
        uses: appleboy/discord-action@v1.2.0
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          message: |
            **Branch:** ${{ github.ref }}
            **Commit:** ${{ github.sha }}



