name: Checkout Code

on:
  push:
    branches:
      - daniel

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          repository: shuttler-tw/shuttler-backend
          ref: daniel

      - name: Setup Node Environment
        uses: actions/setup-node@v4
        with:
          node-version: '22.15.0'
      - run: |
          echo "Node version: $(node -v)"
          echo "Installing dependencies..."
          npm install -g pnpm
          pnpm install
          