name: Lint and Notify

on:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    outputs:
      eslint_output: ${{ steps.eslint.outputs.result }}
      prettier_output: ${{ steps.prettier.outputs.result }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          repository: shuttler-tw/shuttler-backend
          ref: daniel

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.15.0'

      - name: Install dependencies
        run: |
          npm install -g pnpm
          pnpm install

      - name: Run ESLint
        id: eslint
        continue-on-error: true
        run: |
          npm run lint | tee eslint.log
          echo "result<<EOF" >> "$GITHUB_OUTPUT"
          head -n 20 eslint.log >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: Run Prettier Check
        id: prettier
        continue-on-error: true
        run: |
          npm run format:check | tee prettier.log
          echo "result<<EOF" >> "$GITHUB_OUTPUT"
          head -n 20 prettier.log >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

  notify:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Notify on Discord
        uses: appleboy/discord-action@v1.2.0
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          username: 'GITHUB_BOT'
          color: '#48f442'
          message: |
            ✅ **Lint Results**
            🔧 Triggered by: `${{ github.event_name }}`
            📦 Repository: `${{ github.repository }}`
            🌿 Branch: `${{ github.ref }}`
            🔁 Commit: `${{ github.sha }}`

            **ESLint Output:**
            ```
            ${{ needs.lint.outputs.eslint_output }}
            ```

            **Prettier Output:**
            ```
            ${{ needs.lint.outputs.prettier_output }}
            ```

