name: Lint and Notify

on:
  workflow_dispatch: {}
  push:
    branches:
      - daniel

jobs:
  checkout:
    runs-on: ubuntu-latest
    outputs:
      eslint_msg: ${{ steps.eslint.outputs.eslint_msg }}
      prettier_msg: ${{ steps.prettier.outputs.prettier_msg }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          repository: shuttler-tw/shuttler-backend
          ref: daniel

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.15.0'

      - name: Install dependencies
        run: |
          npm install -g pnpm
          pnpm install

      - name: Run ESLint
        id: eslint
        continue-on-error: true
        run: |
          npm run lint | tee "$(date +%F)-eslint.log"
          echo "eslint_msg<<EOF" >> $GITHUB_OUTPUT
          head -n 20 "$(date +%F)-eslint.log" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Run Prettier
        id: prettier
        continue-on-error: true
        run: |
          npm run format:check | tee "$(date +%F)-prettier.log"
          echo "prettier_msg<<EOF" >> $GITHUB_OUTPUT
          head -n 20 "$(date +%F)-prettier.log" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

  notify_discord:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - env:
          ESLINT_MSG: ${{ needs.checkout.outputs.eslint_msg }}
          PRETTIER_MSG: ${{ needs.checkout.outputs.prettier_msg }}
        run: |
            echo "Triggered by: ${{ github.event_name }}"
            echo "Repository: ${{ github.repository }}"
            echo "Branch: ${{ github.ref }}"
            echo "Commit: ${{ github.sha }}"

            echo "ESLint Message: $ESLINT_MSG"

            echo "Prettier Message: $PRETTIER_MSG"