name: Lint and Notify

on:
  workflow_dispatch: {}
  push:
    branches:
      - daniel

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          repository: shuttler-tw/shuttler-backend
          ref: daniel

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.15.0'

      - name: Install dependencies
        run: |
          npm install -g pnpm
          pnpm install

  check_lint:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Run ESLint
        id: eslint
        continue-on-error: true
        run: |
          echo "Current Path: ${PWD}"
          echo "Node Version: $(node -v)"
          echo "NPM Version: $(npm -v)"
          echo "PNPM Version: $(pnpm -v)"
          ls -la
  