name: Lint and Notify

on:
  workflow_dispatch: {}
  push:
    branches:
      - daniel

jobs:
  check_lint:
    runs-on: ubuntu-latest
    outputs:
      eslint_msg: ${{ steps.eslint.outputs.eslint_msg }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          repository: shuttler-tw/shuttler-backend
          ref: daniel

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.15.0'

      - name: Install dependencies
        run: |
          npm install -g pnpm
          pnpm install

      - name: Run ESLint
        id: eslint
        continue-on-error: true
        run: |
          npm run lint | tee "$(date +%F)-eslint.log"
          echo "eslint_msg<<EOF" >> $GITHUB_OUTPUT
          head -n 20 "$(date +%F)-eslint.log" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
  
  check_prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          repository: shuttler-tw/shuttler-backend
          ref: daniel

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.15.0'

      - name: Install dependencies
        run: |
          npm install -g pnpm
          pnpm install

      - name: Run Prettier
        id: prettier
        continue-on-error: true
        run: |
          npm run format:check | tee "$(date +%F)-prettier.log"
          echo "prettier_msg<<EOF" >> $GITHUB_OUTPUT
          head -n 20 "$(date +%F)-prettier.log" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

  notify_discord:
    runs-on: ubuntu-latest
    needs: [check_lint, check_prettier]
    steps:
      - env:
          ESLINT_MSG: ${{ needs.check_lint.outputs.eslint_msg }}
        name: Notify on Discord
        uses: appleboy/discord-action@v1.2.0
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          color: "#48f442"
          username: 'GITHUB_BOT'
          message: |
            Triggered by: `${{ github.event_name }}`
            Repository: `${{ github.repository }}`
            Branch: `${{ github.ref }}`
            Commit: `${{ github.sha }}`

            Check ESLint: "${ESLINT_MSG}"