name: Lint and Notify

on:
  workflow_dispatch: {}
  push:
    branches:
      - daniel

jobs:
  checkout:
    runs-on: ubuntu-latest
    outputs:
      eslint_status: ${{ steps.eslint.outcome }}
      eslint_msg: ${{ steps.eslint.outputs.eslint_msg }}
      prettier_status: ${{ steps.prettier.outcome }}
      prettier_msg: ${{ steps.prettier.outputs.prettier_msg }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          repository: shuttler-tw/shuttler-backend
          ref: daniel

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.15.0'

      - name: Install dependencies
        run: |
          npm install -g pnpm
          pnpm install

      - name: Run ESLint
        id: eslint
        continue-on-error: true
        run: |
          npm run lint | tee "$(date +%F)-eslint.log"
          echo "eslint_msg<<EOF" >> $GITHUB_OUTPUT
          head -n 20 "$(date +%F)-eslint.log" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Run Prettier
        id: prettier
        continue-on-error: true
        run: |
          npm run format:check | tee "$(date +%F)-prettier.log"

          if [ $? -eq 0 ]; then
            echo "prettier_status=success" >> $GITHUB_OUTPUT
          else
            echo "prettier_status=failure" >> $GITHUB_OUTPUT
          fi

          echo "prettier_msg<<EOF" >> $GITHUB_OUTPUT
          head -n 20 "$(date +%F)-prettier.log" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

  check_lint:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - env:
          ESLINT_MSG: ${{ needs.checkout.outputs.eslint_msg }}
        run: |
            echo "Triggered by: ${{ github.event_name }}"
            echo "Repository: ${{ github.repository }}"
            echo "Branch: ${{ github.ref }}"
            echo "Commit: ${{ github.sha }}"

            echo "ESLint Check Status: ${{ needs.checkout.outputs.eslint_status }}"
            echo "ESLint Message: $ESLINT_MSG"

  check_prettier:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - env:
          PRETTIER_MSG: ${{ needs.checkout.outputs.prettier_msg }}
        run: |
            echo "Triggered by: ${{ github.event_name }}"
            echo "Repository: ${{ github.repository }}"
            echo "Branch: ${{ github.ref }}"
            echo "Commit: ${{ github.sha }}"

            echo "Prettier Check Status: ${{ needs.checkout.outputs.prettier_status }}"
            echo "Prettier Message: $PRETTIER_MSG"

  notify_lint_discord:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Notify ESLint to Discord
        if: always()
        uses: appleboy/discord-action@v1.2.0
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          # color: ${{ needs.checkout.outputs.eslint_status == 'success' && '#48f442' || '#ff0000' }}
          color: ${{ startsWith(needs.checkout.outputs.eslint_status, 'success') && '#48f442' || '#ff0000' }}
          username: 'GITHUB_BOT'
          message: |
            **ESLint Check Status:** `${{ needs.checkout.outputs.eslint_status }}`
            Triggered by: `${{ github.event_name }}`
            Repository: `${{ github.repository }}`
            Branch: `${{ github.ref }}`
            Commit: `${{ github.sha }}`

            ```
            ${{ needs.checkout.outputs.eslint_msg }}
            ```